package com.flc.info;

import java.time.LocalDate;

/**
 * Class that constructs each item by the specified attributes for the "all_software" database
 * @author Federico Latorre
 *
 */
public class GeneralSoftware {
	
	/**
	 * auto generated by the DB, unique for each entry
	 */
	private Long id;
	/**
	 * it shows to which system the game was released
	 */
	private String system;
	/**
	 * it shows the name of the game
	 */
	private String game;
	/**
	 * it shows the genre of the game
	 */
	private String genre;
	/**
	 * it shows the company that released the game
	 */
	private String publisher;
	/**
	 * it shows when was the game originally released
	 * Worst kind of variable to deal with
	 */
	private LocalDate releaseDate;
	/**
	 * it shows the game's official recommended price 
	 */
	private int price;
	/**
	 * @param id auto generated by the DB, unique for each entry
	 * @param system it shows to which system the game was released
	 * @param game it shows the name of the game
	 * @param genre it shows the genre of the game
	 * @param publisher it shows the company that released the game
	 * @param releaseDate it shows when was the game originally released
	 * @param price it shows the game's official recommended price 
	 */
	public GeneralSoftware(Long id, String system, String game, String genre, String publisher, LocalDate releaseDate,
			int price) {
//		super();
		this.id = id;
		this.system = system;
		this.game = game;
		this.genre = genre;
		this.publisher = publisher;
		this.releaseDate = releaseDate;
		this.price = price;
	}
	
	/**
	 * @param system it shows to which system the game was released
	 * @param game it shows the name of the game
	 * @param genre it shows the genre of the game
	 * @param publisher it shows the company that released the game
	 * @param releaseDate it shows when was the game originally released
	 * @param price it shows the game's official recommended price 
	 */
	public GeneralSoftware(String system, String game, String genre, String publisher, LocalDate releaseDate,
			int price) {
//		super();
		this.system = system;
		this.game = game;
		this.genre = genre;
		this.publisher = publisher;
		this.releaseDate = releaseDate;
		this.price = price;
	}

	/**
	 * @param id auto generated by the DB, unique for each entry
	 */
	public GeneralSoftware(Long id) {
//		super();
		this.id = id;
	}

	/**
	 * 
	 */
	public GeneralSoftware() {
//		super();
	}

	/**
	 * @return the id
	 */
	public Long getId() {
		return id;
	}

	/**
	 * @param id the id to set
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * @return the system
	 */
	public String getSystem() {
		return system;
	}

	/**
	 * @param system the system to set
	 */
	public void setSystem(String system) {
		this.system = system;
	}

	/**
	 * @return the game
	 */
	public String getGame() {
		return game;
	}

	/**
	 * @param game the game to set
	 */
	public void setGame(String game) {
		this.game = game;
	}

	/**
	 * @return the genre
	 */
	public String getGenre() {
		return genre;
	}

	/**
	 * @param genre the genre to set
	 */
	public void setGenre(String genre) {
		this.genre = genre;
	}

	/**
	 * @return the publisher
	 */
	public String getPublisher() {
		return publisher;
	}

	/**
	 * @param publisher the publisher to set
	 */
	public void setPublisher(String publisher) {
		this.publisher = publisher;
	}

	/**
	 * @return the releaseDate
	 */
	public LocalDate getReleaseDate() {
		return releaseDate;
	}

	/**
	 * @param releaseDate the releaseDate to set
	 */
	public void setReleaseDate(LocalDate releaseDate) {
		this.releaseDate = releaseDate;
	}

	/**
	 * @return the price
	 */
	public int getPrice() {
		return price;
	}

	/**
	 * @param price the price to set
	 */
	public void setPrice(int price) {
		this.price = price;
	}
	
	@Override
	public String toString() {
//		return "SalesInfo [pos=" + pos + ", platoform=" + platform + ", name=" + game + ", publisher=" + publisher
//				+ ", releaseDate=" + releaseDate + ", price=" + price + "]";
		return " [" + system + "] " + game + " <" + genre + "> (" + publisher + ") " + "{" + releaseDate + "} " + "(¥" + price + ")" ;
	}
//	01./00. [NSW] Animal Crossing: New Horizons # <ETC> (Nintendo) {2020.03.20} (¥5.980) - 1.880.626 / NEW <80-100%>
	
}
