package com.flc.info;

import java.time.LocalDate;

/**
 * Class that constructs each item by the specified attributes
 * @author Federico Latorre
 *
 */
public class SoftwareInfo {
	
	/**
	 * auto generated by the DB, unique for each entry
	 */
	private Long id;
	/**
	 * it shows the current position and the last week position
	 */
	private String pos;
	/**
	 * it shows to which system the game was released
	 */
	private String system;
	/**
	 * it shows the name of the game
	 */
	private String game;
	/**
	 * it shows the genre of the game
	 */
	private String genre;
	/**
	 * it shows the company that released the game
	 */
	private String publisher;
	/**
	 * it shows when was the game originally released
	 * Worst kind of variable to deal with
	 */
	private LocalDate releaseDate;
	/**
	 * it shows the game's official recommended price 
	 */
	private int price;
	/**
	 * the sales obtained by the specified week
	 */
	private int sales;
	/**
	 * the accumulated sales of the current SKU
	 */
	private int totalSales;
	/**
	 * how much of the weekly stock was sold
	 */
	private String sellthrough;
	/**
	 * the increment/decrease of units sold between the current week and the last one
	 */
	private Double comparison;
	/**
	 * which week is the current sales
	 */
	private int week;
	

	/**
	 * @param id auto generated by the DB
	 * @param pos it shows the current position and the last week position
	 * @param system it shows to which system the game was released
	 * @param game it shows the name of the game
	 * @param genre it shows the genre of the game
	 * @param publisher it shows the company that released the game
	 * @param releaseDate it shows when was the game originally released
	 * @param price the sales obtained by the specified week
	 * @param sales the sales obtained by the specified week
	 * @param totalSales the accumulated sales of the current SKU
	 * @param sellthrough how much of the weekly stock was sold
	 * @param comparison the increment/decrease of units sold between the current week and the last one
	 */
	public SoftwareInfo(Long id, String pos, String system, String game, String genre, String publisher,
			LocalDate releaseDate, int price, int sales, int totalSales, String sellthrough, Double comparison) {
//		super();
		this.id = id;
		this.pos = pos;
		this.system = system;
		this.game = game;
		this.genre = genre;
		this.publisher = publisher;
		this.releaseDate = releaseDate;
		this.price = price;
		this.sales = sales;
		this.totalSales = totalSales;
		this.sellthrough = sellthrough;
		this.comparison = comparison;
	}

	/**
	 * @param pos it shows the current position and the last week position
	 * @param system it shows to which system the game was released
	 * @param game it shows the name of the game
	 * @param genre it shows the genre of the game
	 * @param publisher it shows the company that released the game
	 * @param releaseDate it shows when was the game originally released
	 * @param price it shows the game's official recommended price 
	 * @param sales the sales obtained by the specified week
	 * @param totalSales the accumulated sales of the current SKU
	 * @param sellthrough how much of the weekly stock was sold
	 * @param comparison the increment/decrease of units sold between the current week and the last one
	 */
	public SoftwareInfo(String pos, String system, String game, String genre, String publisher, LocalDate releaseDate,
			int price, int sales, int totalSales, String sellthrough, Double comparison) {
//		super();
		this.pos = pos;
		this.system = system;
		this.game = game;
		this.genre = genre;
		this.publisher = publisher;
		this.releaseDate = releaseDate;
		this.price = price;
		this.sales = sales;
		this.totalSales = totalSales;
		this.sellthrough = sellthrough;
		this.comparison = comparison;
	}

	/**
	 * @param pos it shows the current position and the last week position
	 * @param system it shows to which system the game was released
	 * @param game it shows the name of the game 
	 * @param genre it shows the genre of the game
	 * @param publisher it shows the company that released the game
	 * @param releaseDate it shows when was the game originally released
	 * @param price it shows the game's official recommended price 
	 * @param sales the sales obtained by the specified week
	 * @param totalSales the accumulated sales of the current SKU
	 * @param sellthrough how much of the weekly stock was sold
	 * @param comparison the increment/decrease of units sold between the current week and the last one
	 * @param week which week is the current sales
	 */
	public SoftwareInfo(String pos, String system, String game, String genre, String publisher, LocalDate releaseDate,
			int price, int sales, int totalSales, String sellthrough, Double comparison, int week) {
//		super();
		this.pos = pos;
		this.system = system;
		this.game = game;
		this.genre = genre;
		this.publisher = publisher;
		this.releaseDate = releaseDate;
		this.price = price;
		this.sales = sales;
		this.totalSales = totalSales;
		this.sellthrough = sellthrough;
		this.comparison = comparison;
		this.week = week;
	}
	
	/**
	 * @param id auto generated by the DB, unique for each entry
	 * @param pos it shows the current position and the last week position
	 * @param system it shows to which system the game was released
	 * @param game it shows the name of the game  it shows the genre of the game
	 * @param genre it shows the genre of the game
	 * @param publisher it shows the company that released the game
	 * @param releaseDate it shows when was the game originally released
	 * @param price it shows the game's official recommended price 
	 * @param sales the sales obtained by the specified week
	 * @param totalSales the accumulated sales of the current SKU
	 * @param sellthrough how much of the weekly stock was sold
	 * @param comparison the increment/decrease of units sold between the current week and the last one
	 * @param week which week is the current sales
	 */
	public SoftwareInfo(Long id, String pos, String system, String game, String genre, String publisher, LocalDate releaseDate, int price,
			int sales, int totalSales, String sellthrough, Double comparison, int week) {
//		super();
		this.id = id;
		this.pos = pos;
		this.system = system;
		this.game = game;
		this.genre = genre;
		this.publisher = publisher;
		this.releaseDate = releaseDate;
		this.price = price;
		this.sales = sales;
		this.totalSales = totalSales;
		this.sellthrough = sellthrough;
		this.comparison = comparison;
		this.week = week;
	}

	/**
	 * @param system it shows to which system the game was released
	 * @param game it shows the name of the game 
	 * @param genre it shows the genre of the game
	 * @param publisher it shows the company that released the game
	 * @param releaseDate it shows when was the game originally released
	 * @param price it shows the game's official recommended price 
	 */
	public SoftwareInfo(String system, String game, String genre, String publisher, LocalDate releaseDate, int price) {
//		super();
		this.system = system;
		this.game = game;
		this.genre = genre;
		this.publisher = publisher;
		this.releaseDate = releaseDate;
		this.price = price;
	}

	/**
	 * @param game it shows the name of the game 
	 */
	public SoftwareInfo(String game) {
		super();
		this.game = game;
	}

	/**
	 * @param id auto generated by the DB, unique for each entry
	 */
	public SoftwareInfo(Long id) {
//		super();
		this.id = id;
	}
	
	/**
	 * 
	 */
	public SoftwareInfo() {
		
	}

	/**
	 * @return the id
	 */
	public Long getId() {
		return id;
	}

	/**
	 * @param id the id to set
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * @return the pos
	 */
	public String getPos() {
		return pos;
	}
	
	/**
	 * @param pos the pos to set
	 */
	public void setPos(String pos) {
		this.pos = pos;
	}
	
	/**
	 * @return the system
	 */
	public String getSystem() {
		return system;
	}
	
	/**
	 * @param system the system to set
	 */
	public void setSystem(String system) {
		this.system = system;
	}
	
	/**
	 * @return the game
	 */
	public String getGame() {
		return game;
	}
	
	/**
	 * @param game the game to set
	 */
	public void setGame(String game) {
		this.game = game;
	}
	
	/**
	 * @return the genre
	 */
	public String getGenre() {
		return genre;
	}

	/**
	 * @param genre the genre to set
	 */
	public void setGenre(String genre) {
		this.genre = genre;
	}

	/**
	 * @return the publisher
	 */
	public String getPublisher() {
		return publisher;
	}
	
	/**
	 * @param publisher the publisher to set
	 */
	public void setPublisher(String publisher) {
		this.publisher = publisher;
	}
	
	/**
	 * @return the releaseDate
	 */
	public LocalDate getReleaseDate() {
		return releaseDate;
	}
	
	/**
	 * @param releaseDate the releaseDate to set
	 */
	public void setReleaseDate(LocalDate releaseDate) {
		this.releaseDate = releaseDate;
	}
	
	/**
	 * @return the price
	 */
	public int getPrice() {
		return price;
	}
	
	/**
	 * @param price the price to set
	 */
	public void setPrice(int price) {
		this.price = price;
	}

	/**
	 * @return the sales
	 */
	public int getSales() {
		return sales;
	}

	/**
	 * @param sales the sales to set
	 */
	public void setSales(int sales) {
		this.sales = sales;
	}

	/**
	 * @return the totalSales
	 */
	public int getTotalSales() {
		return totalSales;
	}

	/**
	 * @param totalSales the totalSales to set
	 */
	public void setTotalSales(int totalSales) {
		this.totalSales = totalSales;
	}

	/**
	 * @return the sellthrough
	 */
	public String getSellthrough() {
		return sellthrough;
	}

	/**
	 * @param sellthrough the sellthrough to set
	 */
	public void setSellthrough(String sellthrough) {
		this.sellthrough = sellthrough;
	}

	/**
	 * @return the comparison
	 */
	public Double getComparison() {
		return comparison;
	}

	/**
	 * @param comparison the comparison to set
	 */
	public void setComparison(Double comparison) {
		this.comparison = comparison;
	}

	/**
	 * @return the week
	 */
	public int getWeek() {
		return week;
	}

	/**
	 * @param week the week to set
	 */
	public void setWeek(int week) {
		this.week = week;
	}

	@Override
	public String toString() {
//		return "SalesInfo [pos=" + pos + ", platoform=" + platform + ", name=" + game + ", publisher=" + publisher
//				+ ", releaseDate=" + releaseDate + ", price=" + price + "]";
		return pos + " [" + system + "] " + game + " <" + genre + "> (" + publisher + ") " + "{" + releaseDate + "} " + "(¥" + price + ") - " + sales + " / " + totalSales + " <" + sellthrough + "> (" + (comparison *100) + "%)" ;
	}
//	01./00. [NSW] Animal Crossing: New Horizons # <ETC> (Nintendo) {2020.03.20} (¥5.980) - 1.880.626 / NEW <80-100%> 
	
}
